version: "3.0"

services:
  nats:
    build:
      context: "./nats"
    expose:
      - "4222"
    ports:
      - "4222:4222"
      - "8222:8222"
    hostname: nats-server

  api:
    build:
      context: "./api"
    depends_on:
      - nats
    labels:
      - "traefik.backend=api"
      - "traefik.frontend.rule=PathPrefix: /api"
      - "traefik.port=8789"
      - "traefik.frontend.entryPoints=http"
    environment:
      NATS_URL: nats://nats:4222
      NATS_USER: ruser
      NATS_PW: T0pS3cr3t
      API_PORT: 8789
      API_HOST: 0.0.0.0
      HEMERA_LOG_LEVEL: silent

  my-subtraction:
    labels:
      id: "da8d9fae.39951"
      description: Subtraction
      node-red: true
      framework: hemera
      topic: math
      pattern: "{topic: 'math', cmd: 'sub'}"
    build:
      context: "./services/my-subtraction"

  my-addition:
    labels:
      id: "da8d9fae.39952"
      description: Addition
      node-red: true
      framework: hemera
      topic: math
      maxMessages: 5
      pattern: "{topic: 'math', cmd: 'add'}"
    build:
      context: "./services/my-addition"
    links:
      - nats
    depends_on:
      - nats
    restart: always
    environment:
      NATS_URL: nats://nats:4222
      NATS_USER: ruser
      NATS_PW: T0pS3cr3t
      HEMERA_LOG_LEVEL: silent

  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "8182:80"
      - "8181:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
